version: 2

project_name: gci

builds:
  - id: gci
    main: ./main.go
    binary: gci
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: gci
    ids:
      - gci
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: []

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  draft: false
  prerelease: auto
